### ISSUE TITLE
Hotkey "Comment with Line Comment" don't work in HOCON editor

### ISSUE THREAD

**Issue by ihostage** [JetBrains/intellij-hocon#12]
"Comment with Block Comment" also not work.

**Comment by ghik** [comment]
Hello @ihostage, I cannot reproduce your issue with Line Comment in plugin version 2019.1.2.
"Comment with Block Comment" cannot work because HOCON doesn't have block comments.

**Comment by ihostage** [comment]
My version of IDEA:
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
Licensed to Sergey Morgunov
Subscription is active until January 10, 2020
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
```

**Comment by ghik** [comment]
Please also provide your HOCON plugin version.

**Comment by ihostage** [comment]
`v2019.1.2`
http://joxi.ru/RmzN9pMcYv8zkm

**Comment by ghik** [comment]
Everything works fine for me with exactly the same versions on Community Edition.
Maybe there's some plugin that conflicts with HOCON on your Ultimate installation? `*.conf` is a common file extension which may be used by other file formats. I can't confirm this because I don't have Ultimate edition. @mutcianm can you comment?

**Comment by ihostage** [comment]
Sorry, @ghik !
